language: php
dist: xenial

# Adjust the version of PHP to match your production environment.
# Making this version number greater than the production environment can have unintended consequences
# including a non-functional prod environment.
php: "7.2"

env:
  global:
    - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
    - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt
    - LOCAL_BLT_DIR=$TRAVIS_BUILD_DIR/blt/
    - BUILD_DIR=$TRAVIS_BUILD_DIR


cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"
    - "$HOME/.nvm"
    - "vendor"
    # Cache front end dependencies to dramatically improve build time.
    - "docroot/themes/custom/chew/node_modules"
    - "docroot/themes/custom/uwmed/node_modules"
    - "docroot/themes/custom/uwmbase/node_modules"
    - ".rules"

services:
- mysql

addons:
  # ssh_known_hosts:
  #   - svn-4786.devcloud.hosting.acquia.com
  chrome: stable

# @see https://docs.travis-ci.com/user/notifications
# notifications:
#   - hipchat: [api token]@[room id or name]
#   - slack: '<account>:<token>#[channel]'

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate --no-check-all --ansi
  - composer install
  # Exit build early if only documentation was changed in a Pull Request.
  - source ${BLT_DIR}/scripts/travis/exit_early

install:
  - source ${LOCAL_BLT_DIR}/custom-scripts/travis/setup_environment
  - source ${LOCAL_BLT_DIR}/custom-scripts/travis/setup_project

script:
  - source ${BLT_DIR}/scripts/travis/run_tests

deploy:
   - provider: script
     script: "${LOCAL_BLT_DIR}/custom-scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: stage
       php: 7.2
   - provider: script
     script: "${LOCAL_BLT_DIR}/custom-scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: develop
       php: 7.2
   - provider: script
     script: "${LOCAL_BLT_DIR}/custom-scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: master
       php: 7.2
   - provider: script
     script: "${LOCAL_BLT_DIR}/custom-scripts/travis/deploy_tag"
     skip_cleanup: true
     on:
       tags: true
       php: 7.2
