language: php
dist: xenial

# Adjust the version of PHP to match your production environment.
# Making this version number greater than the production environment can have unintended consequences
# including a non-functional prod environment.
php: "7.2"

env:
  global:
    - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
    - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt
    - LOCAL_BLT_DIR=$TRAVIS_BUILD_DIR/blt/
    - BUILD_DIR=$TRAVIS_BUILD_DIR
    - UWM_BLT=$TRAVIS_BUILD_DIR/blt/

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
  # Cache front end dependencies to dramatically improve build time.
  # - "docroot/themes/custom/mytheme/node_modules"
  # - "docroot/themes/custom/mytheme/bower_components"

services:
- mysql

addons:
  ssh_known_hosts:
    - svn-23450.prod.hosting.acquia.com
    - uwmeddev.ssh.prod.acquia-sites.com
  chrome: stable

# @see https://docs.travis-ci.com/user/notifications
# notifications:
#   - hipchat: [api token]@[room id or name]
#   - slack: '<account>:<token>#[channel]'

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate --no-check-all --ansi
  - composer install
  # Exit build early if only documentation was changed in a Pull Request.
  - source ${BLT_DIR}/scripts/travis/exit_early

install:
  - source ${UWM_BLT}/custom-scripts/travis/setup_environment
  - source ${UWM_BLT}/custom-scripts/travis/setup_project

script: []
  # Uncomment these lines to test database updates using live content.
  # - blt drupal:sync:default:site
  # Temporarily disable tests
  # - source ${BLT_DIR}/scripts/travis/run_tests
  # - source ${BLT_DIR}/scripts/travis/simulate_deploy

# The version below MUST match the php version indicated at the top of this file, otherwise the artifact won't build.
#deploy:
#   - provider: script
#     script: "${UWM_BLT}/custom-scripts/travis/deploy_branch"
#     skip_cleanup: true
#     on:
#       branch: stage
#       php: 7.2
#   - provider: script
#     script: "${UWM_BLT}/custom-scripts/travis/deploy_branch"
#     skip_cleanup: true
#     on:
#       branch: develop
#       php: 7.2
#   - provider: script
#     script: "${UWM_BLT}/custom-scripts/travis/deploy_branch"
#     skip_cleanup: true
#     on:
#       branch: master
#       php: 7.2
#   - provider: script
#     script: "${UWM_BLT}/custom-scripts/travis/deploy_tag"
#     skip_cleanup: true
#     on:
#       tags: true
#       php: 7.2
