#!/usr/bin/env bash

# Ordinarily we'd use set -e here but that breaks travis_wait, so we use return
# pattern below.

set -v
set +e

vendor/bin/blt validate:all --no-interaction || true

#
# travis_wait vendor/bin/blt setup --define drush.alias='${drush.aliases.ci}' --no-interaction --verbose || { set +v && return 1; }
#
# vendor/bin/blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --no-interaction --verbose || { set +v && return 1; }
#
vendor/bin/blt tests:all --no-interaction --verbose || true

# Run the import/ export compare that is run on
# Acquia following code-deploys. Errors here can prevent
# installing a build.
vendor/bin/blt artifact:update:drupal  --no-interaction --verbose --site=chew
vendor/bin/blt artifact:update:drupal  --no-interaction --verbose --site=huddle
vendor/bin/blt artifact:update:drupal  --no-interaction --verbose --site=stevie



set +v
set -e
