#!/usr/bin/env bash

# Ordinarily we'd use set -e here but that breaks travis_wait, so we use return
# pattern below.

set -v
set +e

echo "TRAVIS_BRANCH: ${TRAVIS_BRANCH}"
pwd

cd tests/nightwatch

npm install nightwatch
npm install geckodriver --save-dev
npm install chromedriver --save-dev


npm install
npm run tests -- --tag rar 


cd -
pwd
set +v
set -e
