#!/usr/bin/env bash

# Ordinarily we'd use set -e here but that breaks travis_wait, so we use return
# pattern below.

set -v

if [[ "${RUN_UWM_TESTS}" == false ]]; then

  echo "UWM: RUN_UWM_TESTS false, so exiting early"
  travis_terminate 0

fi

echo date

vendor/bin/blt validate:all --no-interaction || { set +v && return 1; }

travis_wait vendor/bin/blt setup --define drush.alias='${drush.aliases.ci}' --no-interaction --verbose || { set +v && return 1; }

vendor/bin/blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --no-interaction --verbose || { set +v && return 1; }

echo date


set +v
