#!/usr/bin/env bash

set -ev

# Allow MySQL to finish starting.
sleep 3


# Create MySQL DBs.
mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'drupal'@'localhost' IDENTIFIED BY 'drupal'; GRANT ALL ON drupal.* TO 'drupal'@'localhost';"
mysql -u root -e "CREATE DATABASE drupal_chew; GRANT ALL ON drupal_chew.* TO 'drupal'@'localhost';"
mysql -u root -e "CREATE DATABASE drupal_huddle; GRANT ALL ON drupal_huddle.* TO 'drupal'@'localhost';"
mysql -u root -e "CREATE DATABASE drupal_calendar; GRANT ALL ON drupal_stevie.* TO 'drupal'@'localhost';"


set +v
