#!/usr/bin/env bash

set -ev


export PATH=${COMPOSER_BIN}:$PATH

# Create fake mailer.
echo 'max_execution_time = 120' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Enable $_ENV variables in PHP.
echo 'variables_order = "EGPCS"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
# Ensure that always_populate_raw_post_data PHP setting: Not set to -1 does not happen.
echo "always_populate_raw_post_data = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
# Set PHP memory limit to something more realistic.
echo "memory_limit=512M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Set git info.
git config --global user.name "Travis-CI"
git config --global user.email "noreply@travis-ci.org"

# Clear drush release history cache, to pick up new releases.
#rm -f ~/.drush/cache/download/*---updates.drupal.org-release-history-*
# Verify that no git diffs (caused by line ending variation) exist.
# - git diff --exit-code

# Initialize xvfb (see https://docs.travis-ci.com/user/gui-and-headless-browsers)
# sudo apt-get install xvfb
# export DISPLAY=:99.0
# sh -e /etc/init.d/xvfb start

# Installs chromedriver to vendor/bin.
# ${BLT_DIR}/scripts/linux/install-chrome.sh ${COMPOSER_BIN}

# Install gulp globally
npm install -g gulp-cli

# Add ssh key so we can sync drush into the Acqua Cloud
openssl aes-256-cbc -K $encrypted_02aeaa5f32a9_key -iv $encrypted_02aeaa5f32a9_iv -in travis-deploy-key.enc -out travis-deploy-key -d
rm travis-deploy-key.enc
chmod 600 travis-deploy-key
mv travis-deploy-key ~/.ssh/id_rsa

set +v
