#!/usr/bin/env bash

set -vx
set +e

{

 bash
    blt artifact:deploy --verbose --no-interaction --dry-run --ignore-dirty --commit-msg "Automated commit by Travis CI for Build ${TRAVIS_BUILD_ID}"

} || true



set +vx
set -e
