ignored_config_entities:
  - acquia_connector.settings
  - media_acquiadam.settings
  - d8_google_optimize_hide_page.settings
  - 'webform.webform.*'
  - 'google_tag.*'
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
