module:
  acquia_connector: 0
  acquia_contenthub: 0
  acquia_contenthub_diagnostic: 0
  acquia_contenthub_status: 0
  acquia_contenthub_subscriber: 0
  acquia_purge: 0
  acquia_search: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  allowed_formats: 0
  basic_auth: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  breakpoint: 0
  bulk_edit_terms: 0
  ckeditor: 0
  ckeditor_bs_grid: 0
  ckeditor_templates: 0
  ckeditor_templates_ui: 0
  components: 0
  conditional_fields: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  config_update: 0
  conflict: 0
  consumers: 0
  contact: 0
  contact_storage: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  ctools_block: 0
  current_page_crumb: 0
  d8_google_optimize_hide_page: 0
  datetime: 0
  dblog: 0
  diff: 0
  dropzonejs: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  embed: 0
  entity: 0
  entity_block: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference: 0
  entity_reference_revisions: 0
  facets: 0
  facets_pretty_paths: 0
  fallback_formatter: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filebrowser: 0
  filter: 0
  focal_point: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  geolocation: 0
  google_tag: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  image_style_quality: 0
  image_widget_crop: 0
  inline_entity_form: 0
  jsonapi: 0
  key_value: 0
  lightning_api: 0
  lightning_contact_form: 0
  lightning_core: 0
  lightning_media: 0
  lightning_media_audio: 0
  lightning_media_bulk_upload: 0
  lightning_media_document: 0
  lightning_media_image: 0
  lightning_media_instagram: 0
  lightning_media_twitter: 0
  lightning_media_video: 0
  lightning_roles: 0
  lightning_scheduler: 0
  lightning_search: 0
  lightning_workflow: 0
  link: 0
  link_attributes: 0
  linkit: 0
  media: 0
  media_entity_instagram: 0
  media_entity_twitter: 0
  media_library: 0
  memcache: 0
  menu_export: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  migrate: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  moderation_sidebar: 0
  name: 0
  node: 0
  openapi: 0
  openapi_ui: 0
  openapi_ui_redoc: 0
  openapi_ui_swagger: 0
  options: 0
  page_cache: 0
  paragraphs_admin: 0
  paragraphs_type_permissions: 0
  path: 0
  path_redirect_import: 0
  purge: 0
  purge_drush: 0
  purge_processor_cron: 0
  purge_processor_lateruntime: 0
  purge_queuer_coretags: 0
  purge_tokens: 0
  purge_ui: 0
  quickedit: 0
  rabbit_hole: 0
  rdf: 0
  redirect: 0
  responsive_favicons: 0
  responsive_image: 0
  rest: 0
  rh_media: 0
  robotstxt: 0
  schema_metatag: 0
  schema_organization: 0
  schema_web_page: 0
  schema_web_site: 0
  schemata: 0
  schemata_json_schema: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_db: 0
  search_api_location: 0
  search_api_location_geocoder: 0
  search_api_location_views: 0
  search_api_solr: 0
  serialization: 0
  shortcut: 0
  simple_oauth: 0
  simple_oauth_extras: 0
  simple_sitemap: 0
  siteimprove: 0
  smtp: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  uwm_admin_providers: 0
  uwm_commands: 0
  uwm_content_owners: 0
  uwm_import_epic: 0
  uwm_res_import: 0
  uwmcs_extension: 0
  uwmcs_search_teaser: 0
  uwmcs_searchfields: 0
  uwmcs_utils: 0
  uwmed_schema_clinic: 0
  uwmed_schema_physician: 0
  uwmed_uwmcms_gtm: 0
  uwmed_uwmcms_search: 0
  uwmed_uwmcms_sitemap: 0
  uwmed_uwmcms_webforms: 0
  vbo_export: 0
  video_embed_field: 0
  video_embed_media: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_infinite_scroll: 0
  viewsreference: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  views_url_alias_node: 2
  views: 10
  paragraphs: 11
  lightning: 1000
  eu_cookie_compliance: 1001
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  adminimal_theme: 0
  uwmbase: 0
  zen: 0
  uwmedicineorg: 0
profile: lightning
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
