entity_type_groups:
  node:
    res_clinic:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
      schema_medical_clinic: schema_medical_clinic
    res_provider:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
      schema_physician: schema_physician
    uwm_basic_page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    uwm_condition_spotlight:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    uwm_homepage:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    uwm_hub_page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    uwm_medical_service:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    uwm_medical_specialty:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    uwm_quiz:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
