<?php
/**
 * @file
 * Special hooks for uwm_puma_migrations.module.
 */

use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;
use Drupal\node\NodeInterface;

/**
 * Implements hook_migrate_prepare_row().
 */
function uwm_puma_migrations_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration)
{
    $source = $row->getSource();
    foreach ($source as $key => $value) {
        if (is_string($value)) {
            $new_string = mb_convert_encoding($value, 'UTF-8', 'UTF-8');
            $row->setSourceProperty($key, $new_string);
        }

        if (is_null($value)) {
            /***
             * Most columns in the PUMA migrations are listed as "keys" in the migration yml, so we can identify
             * CSV rows as unique. Ensure the row (and those columns) don't have NULL values, because of an error writing
             * NULL to the MySql migration_map table.
             */
            $row->setSourceProperty($key, '');
        }
    }
}
