<?php

/**
 * @file
 * Custom module for Epic eCare MyChart OpenScheduling.
 */

use Drupal\uwmcs_ecare_scheduling\Controller\ECareController;

/**
 * Implements theme_preprocess_node().
 */
function uwmcs_ecare_scheduling_preprocess_node(&$variables) {

  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['node'];

  // Pass Epic/scheduling metadata to node template, for use in appointment
  // actions and flow.
  if ($node->bundle() === 'res_provider') {

    // TODO: direct scheduling field, when added.
    $field_vars = [
      'field_res_ser_id' => 'epic_id',
      'field_res_is_open_scheduling' => 'open_scheduling',
      'field_res_is_direct_scheduling' => 'direct_scheduling',
      'field_res_visit_type_id' => 'visit_type_ids',
    ];

    foreach ($field_vars as $field_name => $var_name) {

      // Default the boolean values to false, otherwise NULL.
      $variables[$var_name] = (in_array($field_name, ['field_res_is_open_scheduling', 'field_res_is_direct_scheduling']) ? FALSE : NULL);

      if ($node->hasField($field_name) && !$node->get($field_name)->isEmpty()) {
        $field = $node->get($field_name);

        switch ($field_name) {
          case 'field_res_ser_id':
            // Get the exact value.
            $variables[$var_name] = $field->first()->getValue()['value'];
            break;

          case 'field_res_is_open_scheduling':
          case 'field_res_is_direct_scheduling':
            // Convert to boolean.
            $variables[$var_name] = (boolean) $field->first()->getValue()['value'];
            break;

          case 'field_res_visit_type_id':
            // Collect multiple values.
            foreach ($field->getValue() as $val) {
              $variables[$var_name][] = $val['value'];
            }
            break;

        }

      }

    }

    /*
    dpm(array_intersect_key($variables, array_flip($field_vars)));
     */

  }

  // TODO: unused?
  if (!empty($variables['node'])
      && $variables['node']->getType() === 'fact_page'
  ) {

    $eCareCtrl = new ECareController();

    $variables['#attached']['library'][] = 'uwmcs_ecare_scheduling/epic-mychart-scheduling';
    $variables['ecare_link'] = $eCareCtrl->eCareLink();
    $variables['ecare_modal'] = $eCareCtrl->eCareWidget();

  }
  // End TODO.
}
