<?php

/**
 * @file
 * Hook implementations and basic functionality for uwmed_uwmcms_search.
 */

use Drupal\Core\Form\FormState;

/**
 * Implements hook_page_attachments_alter().
 *
 * Add libraries for search pages.
 */
function uwmed_uwmcms_search_page_attachments_alter(&$variables) {
  // Get the current path.
  $currentPath = \Drupal::service('path.current')->getPath();

  // Add the location search form library to the location search page.
  if (stripos($currentPath, '/search/locations') !== FALSE) {
    $variables['#attached']['library'][] = 'uwmed_uwmcms_search/location-search-form';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Customizes exposed forms for views.
 */
function uwmed_uwmcms_search_form_views_exposed_form_alter(&$form, $form_state, $form_id) {
  $storage = $form_state->getStorage();

  if (!isset($storage['view'])) {
    return;
  }

  $view = $storage['view'];

  switch ($view->id()) {
    case 'uwm_locations_geo_search':
      _uwmed_uwmcms_search_alter_locations_search_form($form, $form_state);
      break;
  }
}

/**
 * Implements hook_views_pre_view().
 */
function uwmed_uwmcms_search_views_pre_view($view, $display_id, &$args) {
  switch ($view->id()) {
    case 'uwm_locations_geo_search':
      _uwmed_uwmcms_search_views_pre_view_uwm_locations_geo_search($view, $display_id, $args);
      break;
  }
}

/**
 * Implements hook_preprocess_views_view().
 */
function uwmed_uwmcms_search_preprocess_views_view(&$variables) {
  /** @var \Drupal\views\ViewExecutable $view_ex */
  $view_ex = $variables['view'];

  switch ($view_ex->id()) {
    case 'uwm_locations_geo_search':
      _uwmed_uwmcms_search_preprocess_views_view_uwm_locations_geo_search($variables);
      break;
  }
}

/**
 * Customize the locations search form.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormState $form_state
 *   The form state.
 */
function _uwmed_uwmcms_search_alter_locations_search_form(array &$form, FormState $form_state) {

  $form['use_my_location'] = [

    '#type' => 'container',
    '#attributes' => ['class' => ['use-my-location']],

    // Add a button to calculate user coordinates.
    'uml_button' => [
      '#prefix' => '<div class="use-my-location__prefix">' . t('or') . '</div>',
      '#markup' => '<button class="use-my-location__button btn btn-cta btn-cta-link" type="button">' . t('Use my location') . '</button>',
      '#allowed_tags' => ['button'],
    ],

    // Add a hidden field to hold calculated user coordinates.
    'latlng' => [
      '#type' => 'hidden',
      '#default_value' => \Drupal::request()->query->get('latlng'),
      '#attributes' => ['class' => ['use-my-location__coordinates']],
    ],

    // Add a container for a status message.
    'uml_status' => [
      '#markup' => '<div class="use-my-location__status"></div>',
      '#allowed_tags' => ['div'],
    ],

  ];

  $form['location_address_keywords'] = [

    '#type' => 'container',
    '#attributes' => ['class' => ['location-address-keywords']],

    'l' => [

      '#type' => 'textfield',
      '#size' => 30,
      '#default_value' => \Drupal::request()->query->get('l'),
      '#attributes' => [
        'placeholder' => 'Enter a zip code, neighborhood or city...',
        'autocomplete' => 'off',

      ],

      '#field_suffix' => '<a href="#" class="toggle-uml-dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
<div class="dropdown"><div class="dropdown-menu"><a id="umlDropdownLink" href="#">Use my location</a></div></div>
<div class="status-message"></div>',
    ],

  ];

  if (isset($form['s'])) {

    $form['s']['#attributes']['class'][] = 'dm-form-item-collection';
    $form['s']['#attributes']['autocomplete'] = 'off';

    $form['s']['#weight'] = -10;
    $form['location_address_keywords']['#weight'] = -9;

  }

}

/**
 * Alter the uwm_locations_geo_search view in the pre_view phase.
 */
function _uwmed_uwmcms_search_views_pre_view_uwm_locations_geo_search($view, $display_id, $args) {
  $exposed_input = $view->getExposedInput();

  // If the Use My Location coordinates are available, use them for
  // the distance filter.
  if (!empty($exposed_input['latlng'])) {
    $distance_filter = $view->getHandler($display_id, 'filter', 'field_coordinates_geofield_latlong');
    if ($distance_filter) {
      $distance_filter['value']['value'] = $exposed_input['latlng'];
      $view->setHandler($display_id, 'filter', 'field_coordinates_geofield_latlong', $distance_filter);
    }
  }
}

/**
 * Preprocess the uwm_locations_geo_search view.
 *
 * - If searched by location coordinates, retrieve the distance away for each
 *   result row and store it on the node object for use in theming.
 */
function _uwmed_uwmcms_search_preprocess_views_view_uwm_locations_geo_search(&$variables) {
  /** @var \Drupal\views\ViewExecutable $view_ex */
  $view_ex = $variables['view'];

  $result_row_key = 'entity:node/field_res_building:entity:field_coordinates_geofield__distance';

  /** @var \Drupal\views\ResultRow $result_row */
  foreach ($view_ex->result as $i => $result_row) {

    if (!empty($result_row->{$result_row_key})) {

      // Distance is computed/returned in Search API Location module in
      // kilometers.
      $result_distance_km = $result_row->{$result_row_key}[0];
      $result_distance_miles = $result_distance_km / 1.60935;

      $node = &$variables['rows'][0]['#rows'][$i]['#node'];

      // Store on the node object for display in the theme.
      // @see uwmbase/templates/node/node--res-clinic--card.html.twig
      $node->view_field__distance_away_miles = round($result_distance_miles, 1);

      // Set rendered node caching to vary by the 'latlng' query arg, because
      // the distance will change per the coordinates parameter. (The same form
      // input and query parameter are used for both use-my-location and
      // geocoded location name coordinates.)
      // @see _uwmed_uwmcms_search_views_pre_view_uwm_locations_geo_search()
      // @see _uwmed_uwmcms_search_alter_locations_search_form()
      $variables['rows'][0]['#rows'][$i]['#cache']['contexts'][] = 'url.query_args:latlng';

    }

  }

}
