drush:
  aliases:
    remote: '${project.machine_name}.dev'
    local: '${project.machine_name}.local'

target-hooks:
    frontend-setup:
        dir: '${docroot}/themes/custom/uwmed'
        command: 'bash -c "source ~/.nvm/nvm.sh; nvm use $NODE_JS_VERSION; npm install"'
    frontend-build:
        dir: '${docroot}/themes/custom/uwmed'
        command: 'gulp'